//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Admin
{
    public int ID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Title { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
    public string Phone { get; set; }
    public Nullable<bool> IsMale { get; set; }
    public byte[] Photo { get; set; }
    public System.DateTime RegisterDate { get; set; }
}

public partial class AdOwner
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AdOwner()
    {
        this.Advertisements = new HashSet<Advertisement>();
    }

    public int ID { get; set; }
    public string Name { get; set; }
    public string Phone { get; set; }
    public string Email { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Advertisement> Advertisements { get; set; }
}

public partial class AdPhoto
{
    public int ID { get; set; }
    public int AdID { get; set; }
    public byte[] Photo { get; set; }

    public virtual Advertisement Advertisement { get; set; }
}

public partial class Advertisement
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Advertisement()
    {
        this.AdPhotoes = new HashSet<AdPhoto>();
    }

    public int ID { get; set; }
    public decimal Price { get; set; }
    public System.DateTime StartDate { get; set; }
    public System.DateTime EndDate { get; set; }
    public string Postion { get; set; }
    public Nullable<int> UserID { get; set; }
    public Nullable<int> OwnerID { get; set; }
    public Nullable<bool> ApprovalStatus { get; set; }

    public virtual AdOwner AdOwner { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AdPhoto> AdPhotoes { get; set; }
    public virtual User User { get; set; }
}

public partial class Category
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Category()
    {
        this.SubCategories = new HashSet<SubCategory>();
    }

    public int ID { get; set; }
    public string Name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SubCategory> SubCategories { get; set; }
}

public partial class City
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public City()
    {
        this.Properties = new HashSet<Property>();
    }

    public int ID { get; set; }
    public string Name { get; set; }
    public int CountryID { get; set; }

    public virtual Country Country { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Property> Properties { get; set; }
}

public partial class Country
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Country()
    {
        this.Cities = new HashSet<City>();
    }

    public int ID { get; set; }
    public string Name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<City> Cities { get; set; }
}

public partial class Message
{
    public int ID { get; set; }
    public int PropertyID { get; set; }
    public string Content { get; set; }
    public int SenderID { get; set; }

    public virtual Property Property { get; set; }
    public virtual User User { get; set; }
}

public partial class Property
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Property()
    {
        this.Messages = new HashSet<Message>();
        this.PropertyPhotoes = new HashSet<PropertyPhoto>();
        this.Users = new HashSet<User>();
    }

    public int ID { get; set; }
    public int UserID { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public int CityID { get; set; }
    public string Street { get; set; }
    public decimal Price { get; set; }
    public Nullable<bool> IsSold { get; set; }
    public bool ApprovalStatus { get; set; }
    public int NoOfViews { get; set; }
    public int SubCategoryID { get; set; }
    public System.DateTime StartDate { get; set; }

    public virtual City City { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Message> Messages { get; set; }
    public virtual SubCategory SubCategory { get; set; }
    public virtual User User { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PropertyPhoto> PropertyPhotoes { get; set; }
    public virtual SoldProperty SoldProperty { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<User> Users { get; set; }
}

public partial class PropertyPhoto
{
    public int ID { get; set; }
    public int PropertyID { get; set; }
    public byte[] Photo { get; set; }

    public virtual Property Property { get; set; }
}

public partial class SoldProperty
{
    public int PropertyID { get; set; }
    public Nullable<int> BuyerID { get; set; }
    public System.DateTime SellDate { get; set; }
    public bool IsConfirm { get; set; }
    public Nullable<bool> IsExchanged { get; set; }

    public virtual Property Property { get; set; }
    public virtual User User { get; set; }
}

public partial class SubCategory
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SubCategory()
    {
        this.Properties = new HashSet<Property>();
    }

    public int ID { get; set; }
    public int CategoryID { get; set; }
    public string Name { get; set; }

    public virtual Category Category { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Property> Properties { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class User
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {
        this.Advertisements = new HashSet<Advertisement>();
        this.Messages = new HashSet<Message>();
        this.Properties = new HashSet<Property>();
        this.SoldProperties = new HashSet<SoldProperty>();
        this.UserContacts = new HashSet<UserContact>();
        this.Properties1 = new HashSet<Property>();
    }

    public int ID { get; set; }
    public string FirstName { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
    public Nullable<bool> IsMale { get; set; }
    public byte[] Photo { get; set; }
    public System.DateTime RegisterDate { get; set; }
    public Nullable<bool> IsRemoved { get; set; }
    public string LastName { get; set; }
    public string Question { get; set; }
    public string Answer { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Advertisement> Advertisements { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Message> Messages { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Property> Properties { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SoldProperty> SoldProperties { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<UserContact> UserContacts { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Property> Properties1 { get; set; }
}

public partial class UserContact
{
    public int UserID { get; set; }
    public string Phone { get; set; }
    public bool IsPrivate { get; set; }

    public virtual User User { get; set; }
}
