//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class PropertyFinderDBEntities : DbContext
{
    public PropertyFinderDBEntities()
        : base("name=PropertyFinderDBEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Admin> Admins { get; set; }
    public virtual DbSet<AdOwner> AdOwners { get; set; }
    public virtual DbSet<AdPhoto> AdPhotoes { get; set; }
    public virtual DbSet<Advertisement> Advertisements { get; set; }
    public virtual DbSet<Category> Categories { get; set; }
    public virtual DbSet<City> Cities { get; set; }
    public virtual DbSet<Country> Countries { get; set; }
    public virtual DbSet<Message> Messages { get; set; }
    public virtual DbSet<Property> Properties { get; set; }
    public virtual DbSet<PropertyPhoto> PropertyPhotoes { get; set; }
    public virtual DbSet<SoldProperty> SoldProperties { get; set; }
    public virtual DbSet<SubCategory> SubCategories { get; set; }
    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    public virtual DbSet<User> Users { get; set; }
    public virtual DbSet<UserContact> UserContacts { get; set; }
}
